### ISSUE TITLE
Not giving items with new SP world

### ISSUE THREAD

**Issue by ClaudiusMinimus** [brandon3055/CSG#1]
Just started making a new pack and added CSG. The issue is after using the command "/csg_config set" and then creating a new test world I not getting any gear. If I use "/csg_config give" it works fine. I have not yet tested this in multiplayer.

Minecraft 1.16.5
Forge 36.0.15
CustomStartingGear-1.16.4-2.0.0.1-universal.jar

**Comment by brandon3055** [comment]
Thtas odd it should work in single player. Pleae test in multyplayer if you can and i will look into why its not working in SP

**Comment by ClaudiusMinimus** [comment]
I have since tried it on my server and it is the same issue
Here is the link to the pack
https://www.curseforge.com/minecraft/modpacks/create-on-a-potato/files

**Comment by brandon3055** [comment]
Ok a fix has been uploaded. When i ported to 1.16 i decided to make a change so that it would not set the starter gear if there were already items in your inventory. That way if it ever broke and tried to run at a latter time it would not clear your inventory.
But i forgot about the part where other mods add random things to your inventory.

**Comment by ClaudiusMinimus** [comment]
Thanks, it works mostly. The issue is now that it is not adding items from the [Allomancy mod](https://www.curseforge.com/minecraft/mc-mods/allomancy), which adds a random metal flake when a new player joins indicating the Allomancy power assigned--without this, it kind of breaks the mod. In the screenshot, it shows the default inventory minus the Allomancy metal flakes.
Thank you, CM

![image](https://user-images.githubusercontent.com/17887664/107844299-6e1bd200-6d8f-11eb-8f3e-70298dff3970.png)

**Comment by brandon3055** [comment]
Ok so currently the mod wipes everything added by mods so you have total control over what the player spawns with. 
I will add an option to blacklist certain items or mods.

**Comment by brandon3055** [comment]
Ok give that a try. Just run `/csg_config item_deletion_blacklist allomancy`
One thing to note is allomancy gets in first and adds its item so in the screenshot you posted your sword would end up in the next available inventory slot.
You could work around that by adjusting your config so the first slot is left empty.

**Comment by ClaudiusMinimus** [comment]
Works perfectly!
Thanks!
