### ISSUE TITLE
Custom starting gear is quantum entangled when on server

### ISSUE THREAD

**Issue by Darkmega18** [brandon3055/CSG#3]
When I spawn in and give some leather gear and stone tools to everyone in the server. The first person has the gear just fine.

But the next person who spawns and has the stone and leather gear will instead have a copy of the stone and leather gear but at the current durability which they had it at. 

it's a weird bug, I don't know how you made it happen, but it happens. it's not a crash.

**Comment by brandon3055** [comment]
I belive this will fix the issue. Can you please confirm before I push to curse.
https://ss.brandon3055.com/a171f
I forgot to use a copy of the item tags when creating the items to give to the player. So in a way the items were actually linked via their NBT.

**Comment by Darkmega18** [comment]
sure thing. I'll update to it and see what happens.

**Comment by Darkmega18** [comment]
all seems to check out. we did one test where we spawned the gear for each of us and then broke and did stuff. nothing happened.

then one where we spawned gear gear for one, did some stuff with it, then got the other to get gear afterwards to see if any changes occurred, and both came back negative. So seems fixed. :)

**Comment by brandon3055** [comment]
Thank you. I also did some testing and was not able to reproduce the issue with the fix applied. There is now a new build on curse. The build you have should be fine as long as your not using the kit functionality. Turns out that had the same issue.
