### ISSUE TITLE
Draconic Evolution

### ISSUE THREAD

**Issue by Aptitude3402** [brandon3055/CSG#5]
I’m playing on 1.16.5. This’s my current setup. The crystal on the side of the pylon is set to output mode and the ones on the back of the injectors are set to input mode btw. How do I charge the energy core?
![90EE1604-ED11-4D12-ABDF-6F1C97A8D159](https://user-images.githubusercontent.com/109697621/180077138-ebfdb87f-32e7-41b9-996d-8ef13977bd35.png)

**Comment by brandon3055** [comment]
You have it backwards. In this case "Input" refers to input into the crystal network.
Also, this is not the issue tracker for Draconic Evolution.
